### ISSUE TITLE
 Ошибка создания идентификатора платежа. Свяжитесь с отделом поддержки магазина

### ISSUE THREAD

**Issue by Zhezkazganetcs** [begateway/opencart-payment-module#5]
делал по инструкции и на моменте оформления тестового заказа выскочила ошибка

**Comment by likemusic** [comment]
Получил такую же ошибку на OpenCart 1.5.5.1.2.
В логах ошибок (в админке "Система" > "Журнал ошибок" ) можно увидеть более детальную информацию о проблеме.

В моем случае было такое сообщение:

> 2017-10-16 21:06:50 - Payment token request validation errors: {"errors":{"customer":["is invalid"],"customer.email":["is invalid"]},"message":"Customer is invalid. Customer email is invalid"}

Задал в настройках модуля "Заказ и регистрация Simple" валидный e-mail (т.к. в настройках магазина он не был обязательным полем при оформлении заказа) и после этого вроде бы все заработало как надо.
